name: Update Star Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version of the action

      - name: Set up Python
        uses: actions/setup-python@v3  # Use the latest version of the action
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install skyfield pandas

      - name: Run script
        run: python get_constellation_positions.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add star_data.json
          git commit -m 'Update star data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

